<?php
$SAT_CFDI_USES = [
    'G01' => 'Adquisición de mercancías',
    'G02' => 'Devoluciones, descuentos o bonificaciones',
    'G03' => 'Gastos en general',
    'I01' => 'Construcciones',
    'I02' => 'Mobiliario y equipo de oficina por inversiones',
    'I03' => 'Equipo de transporte',
    'I04' => 'Equipo de cómputo y accesorios',
    'I05' => 'Dados, troqueles, moldes, matrices y herramental',
    'I06' => 'Comunicaciones telefónicas',
    'I07' => 'Comunicaciones satelitales',
    'I08' => 'Otra maquinaria y equipo',
    'D01' => 'Honorarios médicos, dentales y gastos hospitalarios',
    'D02' => 'Gastos médicos por incapacidad o discapacidad',
    'D03' => 'Gastos funerales',
    'D04' => 'Donativos',
    'D05' => 'Intereses reales por créditos hipotecarios',
    'D06' => 'Aportaciones voluntarias al SAR',
    'D07' => 'Primas por seguros de gastos médicos',
    'D08' => 'Gastos de transportación escolar',
    'D09' => 'Depósitos en cuentas para el ahorro',
    'D10' => 'Pagos por servicios educativos',
    'S01' => 'Sin efectos fiscales',
    'CP01' => 'Pagos',
    'CN01' => 'Nómina',
];

$SAT_REGIMENES = [
    '601' => 'General de Ley Personas Morales',
    '603' => 'Personas Morales con Fines no Lucrativos',
    '605' => 'Sueldos y Salarios e Ingresos Asimilados a Salarios',
    '606' => 'Arrendamiento',
    '612' => 'Personas Físicas con Actividades Empresariales y Profesionales',
    '616' => 'Sin obligaciones fiscales',
    '621' => 'Incorporación Fiscal',
    '625' => 'Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas',
    '626' => 'Régimen Simplificado de Confianza',
];
